judgehosts:
  hosts:
    judgehost_1:
      ansible_host: 192.168.x.x
      ansible_connection: ssh
      ansible_user: user
      ansible_port: 22
    judgehost_2:
      ansible_host: 192.168.x.x
      ansible_connection: ssh
      ansible_user: user
      ansible_port: 22


all:
  hosts:
    domserver:
      ansible_host: 192.168.x.x
      ansible_connection: ssh
      ansible_user: user
      ansible_port: 22
  children:
    judgehosts:
  vars:
    TIMEZONE: Asia/Taipei
    DOMJUDGE_VERSION: 7.3.0
    DOCKER_RESTART: unless-stopped

    # Database config
    MYSQL_HOST: domjudge_db
    MYSQL_ROOT_PASSWORD: pwd
    MYSQL_USER: domjudge
    MYSQL_PASSWORD: pwd
    MYSQL_DATABASE: domjudge
    MYSQL_DATA_PATH: /srv/domjudge_volume/db
    MYSQL_MAX_CONNECTIONS: 1000
    MYSQL_MAX_ALLOWED_PACKET: 268435456
    MYSQL_INNODB_LOG_FILE_SIZE: 268435456

    # Domserver config
    FPM_MAX_CHILDREN: 40

    # Judgehost config
    DOMSERVER_HOST: 192.168.x.x
    JUDGEHOST_COUNT: 1
    JUDGEDAEMON_USERNAME: judgehost
    JUDGEDAEMON_PASSWORD: pwd