- name: Create domserver internal network
  community.docker.docker_network:
    name: domserver_internal
    internal: true

- name: Create a database
  community.docker.docker_container:
    name: "{{ MYSQL_HOST }}"
    image: mariadb:10.7
    hostname: "{{ MYSQL_HOST }}"
    command: "--max-connections={{ MYSQL_MAX_CONNECTIONS }} --max_allowed_packet={{ MYSQL_MAX_ALLOWED_PACKET }} --innodb_log_file_size={{ MYSQL_INNODB_LOG_FILE_SIZE }}"
    restart_policy: "{{ DOCKER_RESTART }}"
    ports:
      - "33066:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
    volumes:
      - "{{ MYSQL_DATA_PATH }}:/var/lib/mysql"
    networks:
      - name: domserver_internal

- name: Sleep for 15 seconds to wait db
  ansible.builtin.wait_for:
    timeout: 15

- name: Create a domserver
  community.docker.docker_container:
    name: domserver
    image: "domjudge/domserver:{{ DOMJUDGE_VERSION }}"
    restart_policy: "{{ DOCKER_RESTART }}"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ports:
      - "80:80"
    env:
      CONTAINER_TIMEZONE: "{{ TIMEZONE }}"
      MYSQL_HOST: "{{ MYSQL_HOST }}"
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
      FPM_MAX_CHILDREN: "{{ FPM_MAX_CHILDREN | int }}"
    networks:
      - name: bridge
      - name: domserver_internal
