---
- name: Test linux distribution
  hosts: all
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
    - name: Print linux distribution
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"
    - name: Print linux distribution version
      ansible.builtin.debug:
        msg: "{{ ansible_distribution_major_version }}"
